sonata_admin:
    title: 'The Ineluctable'
    title_logo: images/thumb-03.jpg
    dashboard:
        blocks:
            - { type: sonata.admin.block.admin_list, position: left }
    templates:
        edit: 'Admin/edit.html.twig'
        # create: 'Admin/create.html.twig'

sonata_block:
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]