sonata_admin:
    # title: 'The Ineluctable'
    title_logo: images/logo.png
    dashboard:
        blocks:
            - { type: sonata.admin.block.admin_list, position: left }
    templates:
        edit: 'Admin/edit.html.twig'
        # create: 'Admin/create.html.twig'
    assets:
        extra_stylesheets: ['build/css/admin.css']

sonata_block:
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]